name: flutter_text_sniffer
description: "A widget that detects specific patterns within a text and makes them interactive."
version: 8.0.0
homepage: https://github.com/interdev7/flutter_text_sniffer
repository: https://github.com/interdev7/flutter_text_sniffer
issue_tracker: https://github.com/interdev7/flutter_text_sniffer/issues
topics:
  - text
  - regex
  - widget
  - pattern-matching
  - richtext

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

screenshots:
  - description: The text sniffer package logo.
    path: screenshots/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
